### ISSUE TITLE
Rename in list comprehensions and generators does not work as expected

### ISSUE THREAD

**Issue by karthiknadig** [pappasam/jedi-language-server#125]
```python
x = (f for f in [1,2,3,4,5] if f%2==0)
```

Rename 'f' to 'y'.

Expected:
```
x = (y for y in [1,2,3,4,5] if y%2==0)
```

Actual:
```
x = (y for f in [1,2,3,4,5] if f%2==0)
```

**Comment by pappasam** [comment]
Confirmed bug. That said, my result is:

```python
x = (y for y in [1,2,3,4,5] if f%2==0)
```

Since this basically uses Jedi's rename capabilities, this issue can be filed under <https://github.com/davidhalter/jedi>

**Comment by karthiknadig** [comment]
Filed https://github.com/davidhalter/jedi/issues/1767
