### ISSUE TITLE
Feature request: Auto-suggest to add missing import

### ISSUE THREAD

**Issue by karthiknadig** [pappasam/jedi-language-server#126]
Provide a code action to add missing import.

**Comment by pappasam** [comment]
Unfortunately, this feature is neither supported by Jedi at the present nor will it be supported in the near future (per @davidhalter 's comment on Dec 26, 2020). Please see: <https://github.com/davidhalter/jedi-vim/issues/736#issuecomment-751416521> . If it's super important, we can look into submitting a PR, but I'm guessing David hasn't found a way to provide the feature in an accurate, performant way, and he knows the Jedi codebase better than most humans.

**Comment by davidhalter** [comment]
Yeah, I'm sorry but this won't happen at least in the near future. Jedi's architecture is just not built for this...

**Comment by krassowski** [comment]
FYI, there is this: https://github.com/palantir/python-language-server/pull/685

**Comment by karthiknadig** [comment]
I can understand that this might be something that will take a long time. We can close this for now, and revisit this some time in the future.

**Comment by dmerejkowsky** [comment]
There is also [rope](blob/master/docs/library.rst#list-of-refactorings)

I successfully implemented "add imports" and a few other actions using rope for kakoune. See https://git.sr.ht/~dmerej/kak-rope
