### ISSUE TITLE
Auto-complete with signature and docstring preview?

### ISSUE THREAD

**Issue by johnliu55tw** [pappasam/jedi-language-server#129]
# Description
One thing that I see missing compare to Palantir's `python-language-server` is **auto-complete signature/docstring preview**. Here's a demo from https://github.com/ncm2/float-preview.nvim:
[![asciicast](https://asciinema.org/a/232057.svg)](https://asciinema.org/a/232057)

Does jedi-language-server support this? Or maybe there's something wrong with my configuration? I'm using Ale + deoplete for language server integration. Great project BTW!

**Comment by krassowski** [comment]
Could you try setting

```
    "completion": {
      "resolveEagerly": true
    }
```

in `initializationOptions`?

**Comment by pappasam** [comment]
@johnliu55tw yes, it does support those features! That said, you might try the solution @krassowski suggests and see if that fixes any problems with Ale (which I'd also like to address if you're able to provide any logs / more detailed info). Here's a screencast of me using both of those features you mention with coc.nvim:

![preview-and-signature](https://user-images.githubusercontent.com/3723671/114340511-8f3d3c80-9b0c-11eb-8658-7b1598fd8600.gif)

**Comment by johnliu55tw** [comment]
@krassowski @pappasam Thanks that works and now I have the preview! However, now I'm facing another problem: Ale doesn't support changing the configuration of jedi-language-server :crying_cat_face: I had to change the source code of jedi-language-server in order to test this. But this is more like Ale's issue so case closed.
