### ISSUE TITLE
Feature Request: Add IntelliCode compatibility

### ISSUE THREAD

**Issue by DoS007** [pappasam/jedi-language-server#130]
I'm refering to JediLSP used in VSCode (so this is the appropriate repository to ask about this?).

Please add "[IntelliCode ](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode&ssr=false#overview)compatibility". This would allow to get the most used APIs on the top on code completion suggestion (the moved ones are shown with a star).

See: 
![grafik](https://user-images.githubusercontent.com/11618958/114883571-57ccd980-9e05-11eb-8861-d7a46787021e.png) (Source see IntelliCode Link above)

Would be great, Greets, DoS007

**Comment by bew** [comment]
@DoS007 note that IntelliCode is a proprietary addition from microsoft which can be used by their own plugins, you can't just add compatibility with it AFAIK

**Comment by DoS007** [comment]
@bew On pylance's [site ](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) "IntelliCode compatibility" is named. This formulation made me think, that the compatibility is somethings ofther tools also can have. So there probably a matter of knowing the needed api implementation? But this isn't open to see?

**Comment by pappasam** [comment]
@DoS007 thanks for making me aware of IntelliCode! Unfortunately, after some research, it seems that @bew is correct; IntelliCode isn't open source and seems to be tied directly to vscode. To that end, it looks like this would be something that could only be handled by Microsoft itself. If this feature is important to you, I suggest raising it with Microsoft. @karthiknadig has been super helpful and might be able to help you figure this out in the [vscode-python repo](https://github.com/Microsoft/vscode-python).

Note: pylance is a closed-source, vscode-specific extension of the open source pyright project.

**Comment by krassowski** [comment]
It's a trademark, so we cannot use it. We can implement it on our own, providing similar code intelligence functions, as long as those are not MS intellectual property (a case could be made that algorithms are not, but it depends on where you live and sometimes on specific algorithm).

Also, PyLance [is not open source](https://github.com/microsoft/pylance-release/issues/4) (neither is VSCode). And you are not allowed to run PyLance with anything other than VSCode, even VSCodium, see: [VS Code developers prevent running the new PyLance extension on open-source builds of VS Code](https://www.reddit.com/r/linux/comments/k0s8qw/vs_code_developers_prevent_running_the_new/).

However, I would imagine that @karthiknadig can provide more context on the legal side and how far jedi-language-server or any other language server can go when it comes to implementing more advanced code intelligence functions which resemble IntelliCode.

I am quite confident that we can adopt something like my experiment here: https://github.com/krassowski/python-language-server/pull/1

**Comment by DoS007** [comment]
@pappasam @krassowski Thank you both. 

Yeah, a better sorting of the API-Completions would be helpful. PyCharm also has this and it's really nice. 

Learning api usage frequencies using open source repos and converting the result into a lookup-table would be probably best then? So if one types e.g. `csv.` in the lookup-table could be found numbers representing the importance of them and the completion list could be sorted accordingly. 

I'm no machine learning expert and no language-server expert, but wouldn't it be possible to use the power of jedi to "understand" example code so that it would see where it could provide completion suggestion and then simply looks which suggestion was actually used and count those frequencies? So e.g. for objects one would see the order of the most used completions for that object (most used in the example code for learning)?

**Comment by brettcannon** [comment]
The IntelliCode license restricts its use to only Microsoft products, so adding explicit support for it would be only beneficial to the Python extension for VS Code, and I think that's asking a lot for such a specific use-case, so I agree that it probably shouldn't happen.

Now whether jedi-language-server grew a generic extension point to let other code participate in result sorting, that's a more generally interesting idea (although I cannot speak to whether we would have time to provide IntelliCode support via that API).
