### ISSUE TITLE
High CPU usage even after code close

### ISSUE THREAD

**Issue by przemoch1** [pappasam/jedi-language-server#132]
Hey, I have a problem with VS code jedi python server. This issue started some time ago, with one of last updates. I work with code everyday and I have to restart it several times daily cause it generates a lot of CPU load. My CPU usage is still on 100% after hour or two when I work with VS code. When I close application it is still on 100% and I need to close jedi server by hand to make load lower.

![jedi-high-cpu-usage](https://user-images.githubusercontent.com/36879637/115218670-1723d780-a107-11eb-85e8-dbf02a02b462.png)

Today I did update to my VS code to version 1.55.2 and I still face this issue.

**Comment by pappasam** [comment]
@przemoch1 thanks for opening! This is almost certainly an issue with pygls / specific OS types and is already being tracked in this issue: https://github.com/microsoft/vscode-python/issues/15586

I'm closing as a duplicate, feel free to continue the conversation there!
