### ISSUE TITLE
[Question]: Integrating with (e.g.) black (and similar). 

### ISSUE THREAD

**Issue by carltongibson** [pappasam/jedi-language-server#138]
Hi. First off, thanks for the great work. Really enjoying using the jedi-language-server.

I know it's out-of-scope for JLS itself, but I'd like to be able to hook in somehow to run flake8/black/isort on the did save event, whilst letting JLS continue to do it's things. I'm starting to look into the implementation and `pygls` but I'm wondering if you could offer any pointers as to how best to approach this? 

Clearly that's a bit speculative, but any pointers would be gratefully received. 

(Please do close without qualm.) 

Thanks again!

**Comment by pappasam** [comment]
As mentioned [here](https://github.com/pappasam/jedi-language-server#additional-diagnostics), just run [diagnostic-language-server](https://github.com/iamcco/diagnostic-languageserver) in addition to jedi-language-server! If using coc.nvim, I've provided some helpful hints to get you started in [coc-jedi](https://github.com/pappasam/coc-jedi):

- https://github.com/pappasam/coc-jedi#additional-diagnostics
- https://github.com/pappasam/coc-jedi#code-formatting
