### ISSUE TITLE
100% processor usage, eating up more and more RAM

### ISSUE THREAD

**Issue by rwols** [pappasam/jedi-language-server#14]
One of my cores is constantly spinning while this language server runs.
The RAM usage is also steadily rising.

I believe these two issues should be fixed ;)

![Screenshot from 2020-05-01 23-26-16](https://user-images.githubusercontent.com/2431823/80843034-81e0b800-8c03-11ea-8323-1820a8310bbe.png)

**Comment by pappasam** [comment]
@rwols can you please let me know which version you're using?

```bash
jedi-language-server --version
```

Version 0.10.2 fixed a performance issue with highlight, so :crossed_fingers: that might have fixed your issue.

If you're on 0.10.2, then I'll have a fun deep dive into this problem

**Comment by rwols** [comment]
Looks like I was using 0.10.1. I upgraded to 0.10.2 and it seems to be behaving better.

**Comment by pappasam** [comment]
As mentioned above, resolved in 0.10.2. @rwols please re-open if you discover something to the contrary!
