### ISSUE TITLE
Variable type on hover not showing up

### ISSUE THREAD

**Issue by kimadeline** [pappasam/jedi-language-server#141]
(initially reported in https://github.com/microsoft/vscode-python/issues/16187)

When having the following snippet:

```
variable: int = 0

variable + 1  # hover on "variable" should display [int]
```

Hovering on the bottom `variable` doesn't return its type. 

Trace info:
```
[Trace - 2:43:16 PM] Sending request 'textDocument/hover - (8)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/kimiguel/Documents/Sandbox/sample-file/foo.py"
    },
    "position": {
        "line": 2,
        "character": 6
    }
}


INFO:pygls.protocol:Sending data: {"jsonrpc": "2.0", "id": 8, "result": null}
[Trace - 2:43:16 PM] Received response 'textDocument/hover - (8)' in 5ms.
No result returned.
```

**Comment by pappasam** [comment]
@kimadeline Looks like we could get something like this using Jedi's variable description. Would the following be acceptable?

![image](https://user-images.githubusercontent.com/3723671/120532840-f8b32c00-c394-11eb-9368-149ef0a6cf07.png)

Update to Hover would look something like this (will require a bit more work for me to handle edge cases, but I'm pretty sure it'll eventually be an overall improvement):

```python
@SERVER.feature(HOVER)
def hover(
    server: JediLanguageServer, params: TextDocumentPositionParams
) -> Optional[Hover]:
    """Support Hover."""
    document = server.workspace.get_document(params.text_document.uri)
    jedi_script = jedi_utils.script(server.project, document)
    jedi_lines = jedi_utils.line_column(jedi_script, params.position)
    markup_kind = _choose_markup(server)
    docstring: Optional[str] = None
    for name in jedi_script.help(**jedi_lines):
        docstring = name.docstring()
        if docstring:
            break
    if not docstring:
        docstring = name.description
    if not docstring:
        return None
    docstring_clean = jedi_utils.convert_docstring(docstring, markup_kind)
    contents = MarkupContent(kind=markup_kind, value=docstring_clean)
    document = server.workspace.get_document(params.text_document.uri)
    _range = pygls_utils.current_word_range(document, params.position)
    return Hover(contents=contents, range=_range)
```

**Comment by kimadeline** [comment]
That would be great, thank you for looking into it!

**Comment by pappasam** [comment]
Added a bunch of new information and reformatted the existing hover text. Would like your thoughts on the current implementation before I modify the tests: https://github.com/pappasam/jedi-language-server/pull/143

Example output:

![image](https://user-images.githubusercontent.com/3723671/120846027-6f336380-c526-11eb-8824-a26930ed1d4e.png)

**Comment by pappasam** [comment]
I've re-organized / updated the tests. I think this is an overall improvement. I'm sure there are some edge cases out there, but I can't find any at the moment. I'm just going to merge the branch and release since I'd like these features now.

![image](https://user-images.githubusercontent.com/3723671/120863781-fccf7d00-c53f-11eb-942e-c14155cd24cc.png)

**Comment by karthiknadig** [comment]
@pappasam I agree. We can tackle corner cases based on user feedback.

**Comment by pappasam** [comment]
Resolved with latest release
