### ISSUE TITLE
Filtering textDocument/hover results

### ISSUE THREAD

**Issue by JulienPalard** [pappasam/jedi-language-server#147]
Sometimes I find the hover result usefull (on identifiers, for example), sometimes not, and depending on the zoom level it can become a burden. I often use a big font when I teach, for readability, so I often enconter those hovers:

![2021-06-08-113126_1920x1080_scrot](https://user-images.githubusercontent.com/239510/121161241-15e07280-c84d-11eb-875b-b1f3072536f6.png)

I think it would be nice to be able to configure the verbosity here, and say "OK now I know about classes, don't show this huge tooltip again".

**Comment by pappasam** [comment]
@JulienPalard hmm, it should be possible to support this. That said, we should discuss the design before I implement.

Probably the simplest way I can think to support this would be to force the hover LSP method to return `None` for certain Jedi name types. These types are:

        Valid values for type are ``module``, ``class``, ``instance``, ``function``,
        ``param``, ``path``, ``keyword``, ``property`` and ``statement``.

The user could pass, as an InitializationOption, a mapping of name types and values that they might want to return no responses for hover.

For example, one example user configuration could look like this:

```json
{
  "initializationOptions": {
    "hover": {
      "ignoreType": {
        "keyword": ["class"],
        "statement": true
      }
    }
  }
}
```

In this, all "statements" are ignored, and Python keywords with the name "class" are ignored.

How does this design sound to you?

**Comment by JulienPalard** [comment]
> How does this design sound to you?

I still never tried to pass initializationOptions, hope it's not too hard using emacs' lsp-mode :D

Looks good to me.

**Comment by pappasam** [comment]
@JulienPalard for reference, see: https://github.com/pappasam/coc-jedi#jedihoverdisable

Since you're not using Neovim, your initializationOption will look something like this:

```json
{
  "initializationOptions": {
    "hover": {
      "disable": {
        "keyword": {
          "names": ["class"]
        }
      }
    }
  }
}
```

Alternatively, if you want to disable all keyword hovers:

```json
{
  "initializationOptions": {
    "hover": {
      "disable": {
        "keyword": {
          "all": true
        }
      }
    }
  }
}
```

Please let me know if you have any questions, and hope you enjoy the new feature!
