### ISSUE TITLE
Clear diagnostics on document close

### ISSUE THREAD

**Issue by rebornix** [pappasam/jedi-language-server#153]
Currently when a document is closed, the language server doesn't clear diagnostics for the document.

**Comment by pappasam** [comment]
Thanks for opening this issue! Would you please explain why this is a problem and/or why it would be better to explicitly clear diagnostics on document close? I haven't personally found any issues with not clearing diagnostics on document close and it doesn't look like the LSP recommends explicitly clearing diagnostics on document close (at least as of version 3.16).

**Comment by rebornix** [comment]
@pappasam thanks for your quick response, I should provide more insights early. The major scenarios I found it reasonable to clear diagnostics on document close is non-file based documents (in VS Code):

* Untitled document. Create an untitled document, type in `x =` which will generate an error, close the document without saving, the diagnostics don't go away.
* Interactive Window (currently under development). This is similar to untitled python file, but it's a repl like editor which contains a text editor whose mode is python, closing the interactive window will not clear the diagnostics.

For above two scenarios, the source file is in-mem/virtual and they don't belong to current workspace, and when the text document is closed, the diagnostics don't disappear together with the document itself.

> I haven't personally found any issues with not clearing diagnostics on document close and I can't find any documentation where the LSP recommends explicitly clearing diagnostics on document close

Currently this seems a limitation of the language server protocol. TypeScript language server will clear the diagnostics on any text document close, even if it's part of current workspace (it's not necessarily the right behavior). The "correct" behavior is probably keeping the diagnostics only when the file is part of the project/workspace and removing ones which are from other files. But unluckily there is no project concept in LSP afaik.

---

With that being said, I think one possible solution for now is removing diagnostics for non-file text documents?

**Comment by rebornix** [comment]
The changes for supporting disposing diagnostics on text document close is actually trivial https://github.com/rebornix/jedi-language-server/commit/f099f504a63308d4675eda8a513dfa08dc28085d

**Comment by pappasam** [comment]
@rebornix I'm totally open to including this! Just submit a PR and I'll review

**Comment by pappasam** [comment]
Also, @rebornix , assuming diagnostics are enabled, can you think of any reason why we wouldn't want to clear diagnostics on close? Eg, is it necessary to make this configurable, or would it be better just to force diagnostics to always clear on document close? To keep things simple, I prefer to avoid adding user configuration where possible.

**Comment by rebornix** [comment]
@pappasam considering the language server right now is text document based, I think we should always clear diagnostics to be consistent. For example, when users open a workspace without any files opened, users will not see any diagnostics, they would only get diagnostics after opening files in text editor, so it makes sense to me to clear them when they are closed.

One may argue that we should keep it since those files are still in the workspace but I think that should be handled by the language server protocol to support "project". When a project is detected in the workspace, no matter if the document is opened or not, the language server should scan all files in the project and then provide diagnostics. Currently we don't have such concept yet (IIRC) and both TypeScript language server and Pylance will clear diagnostics when a file is closed.

For short, to keep the jedi language server consistent and clean, I'll recommend clearing diagnostics on document close always and we don't introduce a setting to control the behavior. My pr for this change https://github.com/pappasam/jedi-language-server/pull/155 .
