### ISSUE TITLE
Signature help for functools.wraps()-decorated function shows undecorated parameter list

### ISSUE THREAD

**Issue by smheidrich** [pappasam/jedi-language-server#156]
(Moved here from https://github.com/pappasam/coc-jedi/issues/41)

I'm not sure if this is an issue in jedi-language-server or Jedi itself, but I guess I'll ask here first and then we can propagate it "up" to Jedi if it's in their court.

When you have a function that is marked as wrapping another function with `functools.wraps`, the signature help for a call to the former contains the "correct" (in my opinion, anyway) docstring and function name, namely that of the wrapped function, but the "wrong" parameter list, namely that of the wrapping function (which will often be just `*args, **kwargs`). Minimal reproducible example:

```python
from functools import wraps

def f(x: int, y: float):
  "docstring of f"
  pass

@wraps(f)
def g(*ar, **kw):
  f(*ar, **kw)

g()
```

Using coc-jedi in vim and moving the cursor into `g()` shows something like:

![vim-hover](https://user-images.githubusercontent.com/3827982/126628404-7da52f61-23ec-431e-8ebb-a4a9ae1ed37a.png)

The expected result would be for it to show `f(x: int, y: float)` instead.

Now as I said, I'm not sure if this is an issue in jedi-language-server or Jedi. I did some tests using Jedi itself and it seems the call signature returned by jedi-language-server is what you get when you use the immediate result from `Script.get_signatures()`, whereas my "expected" result can be obtained by either re-resolving that signature via its own `get_signatures()` method or its `get_type_hint()` method (the latter is claimed in the Jedi docs to extract the signature from *calls* of this function, which probably isn't what we want here in general - but in this case it happens to be fine):

```python
from jedi import Script

with open("example.py") as f:
  scr = Script(f.read())

sig = scr.get_signatures(11, 2)[0]

print(sig.to_string())                     # f(*ar, **kw)
print(sig.get_signatures()[0].to_string()) # f(x: int, y: float)
print(sig.get_type_hint())                 # f(x: int, y: float)
```

So I guess an easy fix would be to have jedi-language-server apply the 2nd to last line to any function signatures that should go into the hover window, but perhaps it would be better if the "immediate" signature returned by Jedi was already the expected one?

**Comment by smheidrich** [comment]
I've looked into it a bit more and I guess this should really be fixed on the Jedi side of things, shouldn't it? Because using the workaround above, (via `Signature.get_signatures`), we lose the `index` attribute going from a `Signature` to a `BaseSignature` so showing which parameter is currently being filled in no longer works. If this was fixed on Jedi's end, the index would be available as usual.

**Comment by smheidrich** [comment]
I opened an issue for Jedi, https://github.com/davidhalter/jedi/issues/1791, let's see what they say.

**Comment by pappasam** [comment]
@smheidrich Awesome, thanks for opening! I'm following that issue now

**Comment by smheidrich** [comment]
Has been fixed in Jedi, https://github.com/davidhalter/jedi/pull/1793
