### ISSUE TITLE
We are seeing significant performance degradation between 0.31.1 and 0.34

### ISSUE THREAD

**Issue by karthiknadig** [pappasam/jedi-language-server#157]
Related: https://github.com/microsoft/vscode-python/issues/16857

**Comment by pappasam** [comment]
@karthiknadig I don't have access to the report. Would you be able to help me understand what has regressed? I'm guessing it has something to do with the fixes I made to Markdown support on Hover, but I'm not sure...

**Comment by karthiknadig** [comment]
Startup time is about 40% more.

**Comment by pappasam** [comment]
Startup time is the only performance regression? If yes, I can think of a couple reasons:

1. [Added lots of options to filter unwanted hover text](https://github.com/pappasam/jedi-language-server/pull/149/files)
2. Most-likely: [We updated pygls to 0.11](https://github.com/pappasam/jedi-language-server/pull/151)

**Comment by karthiknadig** [comment]
We are investigating this on our end to pin point where this started. But, from perf telemetry looks like it is startup-time regression. I will ping back when we have more info.

**Comment by karthiknadig** [comment]
Closing this, this seems to have been caused by another dependency in the extension.
