### ISSUE TITLE
Redundant new line in signature help

### ISSUE THREAD

**Issue by HansPinckaers** [pappasam/jedi-language-server#158]
Related issue: https://github.com/ray-x/lsp_signature.nvim/issues/56

I'm testing out the native lsp-client inside neovim with compe.nvim and lsp_signature.nvim., I'm seeing an additional newline in the config (also in the resolve information/documentation). I tried removing the `\n` in `_md_text` and `_md_python` which works, but I think the python fencing goes wrong then? I see ``` in my documentation.

**Comment by pappasam** [comment]
@HansPinckaers ah yes, empty docstrings weren't handled correctly here. Thanks for raising, am fixing now!
