### ISSUE TITLE
Completions

### ISSUE THREAD

**Issue by rwols** [pappasam/jedi-language-server#16]
I think this server has potential :) I'm posting a list of things that can be improved about the completions, and I hope we can reach some agreement on this.

```
some_function(arg1, arg2)
-------------
 filterText

-------------------------
         label


insertTextFormat: always put 2 (snippet) for function, 1 (plaintext) for anything else

if the editor can do signatureHelp:
	insertText: some_function($0)
else:
	insertText: some_function(${1:arg1}, ${2:arg2})
```

I'm noticing there are a lot of keys that point to *falsy* values. If the value is falsy, make sure the key isn't present at all. This makes the response payloads much smaller.

**Comment by pappasam** [comment]
Is this issue regarding snippets support in general? I haven't yet implemented this but I'm open to exploring!

**Comment by pappasam** [comment]
Also, what do you mean by "keys that point to falsy values"? What "keys" and "values" are you describing? I'd like to start work on this issue as soon as we've closed https://github.com/pappasam/jedi-language-server/issues/15

**Comment by pappasam** [comment]
@rwols I continue to be confused by this issue. Any clarifying points you'd be able to provide?

**Comment by rwols** [comment]
Apologies for the silence.

These are just recommendations for getting completions to work nicely across editors.

- Add `filterText`: it should be a substring of `label`, preferably only alphanumeric characters. For instance, for a function called `foobar`, the filterText would be... `foobar`. The label would be `foobar(arg1, arg2)`.
- Add `insertTextFormat` field: put `1` as the value if it's a non-snippet, otherwise put `2` if it's a snippet.
- Enhance `insertText`: If the completion is a function, let's call that function `foobar`, then set `insertText` as `foobar($0)` if the editor supports signatureHelp, otherwise set `insertText` as `foobar(${1:arg1}, ${2:arg2})` if the editor doesn't support signatureHelp.

**Comment by pappasam** [comment]
@rwols in the latest release, I've mostly implemented the above with some minor tweaks based on my own personal preferences. When you have the time, please let me know if snippets are working correctly on your end!

**Comment by pappasam** [comment]
Ok, based on my own personal testing, this issue is resolved. Please feel free to open a new issue if you notice anything unsavory about the new snippets feature!
