### ISSUE TITLE
Completion items sort order should be public, private, dunder

### ISSUE THREAD

**Issue by karthiknadig** [pappasam/jedi-language-server#184]
![image](https://user-images.githubusercontent.com/3840081/144489711-8526dbde-d247-4e66-b552-34e9f2634926.png)

**Comment by pappasam** [comment]
@karthiknadig would you be able to show more code? This is very hard to replicated with only the provided screenshot.

Also, this issue may be a duplicate of https://github.com/pappasam/jedi-language-server/issues/131

**Comment by karthiknadig** [comment]
```python
import requests

def print_response(r: requests.Response) -> None:
    print(r.
```
