### ISSUE TITLE
jedi language server complain python 3.10 syntax

### ISSUE THREAD

**Issue by kasfil** [pappasam/jedi-language-server#187]
I have jedi_language_server installed trough `pipx` and python 3.10
but jedi complaining about new python `match` syntax
![Screenshot from 2021-12-14 17-51-13](https://user-images.githubusercontent.com/46927505/145984876-d0184f87-60dd-426a-a939-897afe20f2b7.png)

did i miss some configuration?

**Comment by pappasam** [comment]
@kasfil nope, you're not missing anything! Sadly, it looks like pattern matching syntax isn't yet supported by Jedi.

- https://github.com/davidhalter/jedi/issues/1756
- https://github.com/davidhalter/parso/issues/138

Until that's resolved upstream, I recommend disabling jedi diagnostics if you're relying on the new pattern matching syntax.

- Relevant setting (if you're using coc-jedi): https://github.com/pappasam/coc-jedi#jedidiagnosticsenable
- Configuration object (if you're not using coc-jedi): https://github.com/pappasam/jedi-language-server#configuration
