### ISSUE TITLE
Passing initialization options in VSCode

### ISSUE THREAD

**Issue by MasonMcGill** [pappasam/jedi-language-server#198]
Hi,

Is there a way to configure this language server through VSCode? Specifically, I'd like to turn off diagnostics; having hover-over documentation and drop-down field completion is great, but having red squiggles popping up everywhere as I type is very distracting, like a friend interrupting you mid-sentence to correct your grammar : ). The readme suggests coc-jedi but that looks like some kind of Vim thing?

Thanks in advance!

**Comment by pappasam** [comment]
VSCode abstracts the provided initialization options, so you'll need to reference VSCode's documentation to figure out how to disable diagnostics: https://github.com/microsoft/vscode-python

I'm actually not sure where disabling the relevant diagnostics is documented, but if it's not something you can easily figure out how your own, it might be worth opening an issue with vscode-python (which uses jedi-language-server under the hood, assuming you've set `python.languageServer` to `Jedi`). If you're able to figure it out, please let me know how you did it before closing this issue!

**Comment by MasonMcGill** [comment]
Thanks! It looks like there's already an issue for this (https://github.com/microsoft/vscode-python/issues/17777) and the team is considering how to expose this functionality via the settings menu, so with any luck this will be possible in a future version of the VS Code Python plugin. 🤞🤞

**Comment by pappasam** [comment]
Since this is a VSCode problem, I'll close this issue so conversation can continue at https://github.com/microsoft/vscode-python/issues/17777
