### ISSUE TITLE
How can I search for symbols in a python project from the command line?

### ISSUE THREAD

**Issue by jgarte** [pappasam/jedi-language-server#213]
Hi,

How can I search for symbols from the [command-line](https://github.com/pappasam/jedi-language-server#command-line)?

My use case is that I would like to make a simple CLI tool that allows me to search for lsp project symbols from the command line and pipe the results to fzf preview then pipe my choice to `stdout` as a line number that I can give to [vis](https://github.com/martanne/vis).

`jedi-lsp | xargs -ro vis` 

I realize there is a WIP [lsp client](https://github.com/fischerling/vis-lspc) already for vis but I would like to try this for learning how to use jedi-language-server from `stdio` and for experimentation/hacking.

**Comment by pappasam** [comment]
Hmm... I'm not sure how this might be done, and my gut tells me that a language server is not designed to be interacted with in the way suggested here. `stdio` is just useful. A lot of hoops need to be jumped through to interact with language servers. You can see an example by reading our tests and observing what needs to happen to mock up an LSP client for testing: https://github.com/pappasam/jedi-language-server/blob/main/tests/lsp_test_client/session.py

**Comment by jgarte** [comment]
>  stdio is just useful

Can you explain more on why stdio is a useful feature of `jedi-language-server`? It might not be readily apparent all the use cases in this context.

Thanks for the link. I'll do some more reading.
