### ISSUE TITLE
Are workspace symbols supported? 

### ISSUE THREAD

**Issue by jgarte** [pappasam/jedi-language-server#215]
I ask because I tried using [this package](https://github.com/mohkale/consult-eglot) and it complained that pylsp does not support this feature. It worked well with `pyright`.

Does jedi-language-server support it? I haven't tested it yet...

**Comment by jgarte** [comment]
Actually, it looks like so:

https://github.com/pappasam/jedi-language-server/search?q=workspace

**Comment by jgarte** [comment]
![2022-07-07-210242_1600x900_scrot](https://user-images.githubusercontent.com/47760695/177902062-342dff79-5842-42bf-887b-bfc7d97430d2.png)

**Comment by jgarte** [comment]
Searching for symbols with eglot, eglot-consult, and jedi-language-server in emacs does the wrong thing I think.

**Comment by pappasam** [comment]
In short, yes, workspace symbols are supported. We use the `Project.complete_search` method, documented here: <https://jedi.readthedocs.io/en/latest/docs/api.html#jedi.Project>

For performance reasons, we only search for symbols that are at the top-level of modules. It currently behaves as I would expect it to. What are you expecting the workspace search to do?

**Comment by pappasam** [comment]
Given the lack of activity, I assume this has been resolved. Feel free to re-open if you think there's still an important issue here!
