### ISSUE TITLE
Not able to install jedi language server in python 3.10 due to import metadata dependency 

### ISSUE THREAD

**Issue by mohanrajdtv** [pappasam/jedi-language-server#218]
Here is the error we are getting

_Pinned packages:
  - python 3.10.*
  - python 3.10.5

Encountered problems while solving:
  - package jedi-language-server-0.36.1-pyhd8ed1ab_0 requires importlib-metadata >=3.10.1,<4, but none of the providers can be installed
  - package importlib-metadata-3.10.1-py39hf3d152e_0 requires python >=3.9,<3.10.0a0, but none of the providers can be installed_

Current version of importlib_metadata is 4.11.4 https://anaconda.org/conda-forge/importlib_metadata

**Comment by dimbleby** [comment]
this project explicitly only requires importlib for older versions of python:

```
$ curl -s https://pypi.org/pypi/jedi-language-server/0.36.1/json | jq '.info.requires_dist'
[
  "jedi (>=0.18.1,<0.19.0)",
  "pygls (>=0.12,<0.13)",
  "pydantic (>=1.9.1,<2.0.0)",
  "docstring-to-markdown (<1.0.0)",
  "importlib-metadata (>=3.10.1,<4.0.0); python_version >= \"3.7\" and python_version < \"3.8\""
]
```
so whatever mechanism you are using to install it is wrongly ignoring that.

**Comment by pappasam** [comment]
Given @dimbleby 's observation, I'm going to close this issue and assume there is something wrong with the user's installation process. Feel free to open a new issue if you can provide more information, I'm always happy to add info to the readme if it's helpful to users!
