### ISSUE TITLE
Coc not working with v0.37.0

### ISSUE THREAD

**Issue by Et9797** [pappasam/jedi-language-server#224]
![image](https://user-images.githubusercontent.com/20364007/189499031-1563d975-96d0-4991-a1a8-9755026032de.png)

**Comment by pappasam** [comment]
Not quite sure what the issue is on your machine, but jedi-language-server 0.37.0 does exist on pypi: https://pypi.org/project/jedi-language-server

**Comment by Et9797** [comment]
> Not quite sure what the issue is on your machine, but jedi-language-server 0.37.0 does exist on pypi: https://pypi.org/project/jedi-language-server

Yes I've found the issue to be with the default Python installation on Ubuntu 18, which is Python 3.6.9. v0.37 only supports Python >3.7
