### ISSUE TITLE
[Newbie] Cannot alter extra_paths from neovim lspconfig setup

### ISSUE THREAD

**Issue by dpopchev** [pappasam/jedi-language-server#229]
Using `jedi-vim` I can do `let g:jedi#added_sys_path = ['./lib', './src',]`  and enjoy completion with lookup in local modules.

For the love of God I cannot make it work with neovim, 0.7.2, 0.8, 0.9 in particular. 

I am using `nvim-lsp-installer` to easy install the plugin, then `nvim-lspconfig` in particular. 
Thus extending should happen in the setup, here is what I try:
```
require('lspconfig')['jedi_language_server'].setup{
...
settings = { ... }
root_dir = require("lspconfig/utils").root_pattern(".git") -- ensure root directory is found for proejcts
...
}
```

#### Added references:

- [extraPaths](https://neovim.discourse.group/t/pyright-unable-to-resolve-imports-that-are-in-my-pythonpath/1289), neovim discussions
- [jedi.workspace.extraPaths](https://github.com/pappasam/coc-jedi) , coc-jedi
- [python.autoComplete.extraPaths](https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings), python-language-server
- [nvim-lsp](https://github.com/pwntester/nvim-lsp/blob/master/README.md)

**Comment by pappasam** [comment]
I'm guessing that, in your `setup` function, you'll need to configure the initialization option under the `init_options` parameter.

See: `https://github.com/pappasam/jedi-language-server#configuration`

```json
"workspace": {
      "extraPaths": [],
}

**Comment by pappasam** [comment]
For documentation about this option, see: https://github.com/pappasam/coc-jedi#jediworkspaceextrapaths

**Comment by dpopchev** [comment]
I tired
```
...
settings = {
  extraPaths = { "./lib" }
}
....
```

also per documentation analogue for `pylsp.plugins.pycodestyle.ignore`  for `jed.workspace.extraPaths`
```
...
settings = {
  jedi = {  --also jed_language_server
    workspace = {
      extraPaths = { './lib'}
    }
}
...
```
with no succes, I have no clue how to check value passing for those.

NOTE: I am aware tha I can just append to PYTHONPATH, but I am seeking the flexibility per configuration per project.

**Comment by pappasam** [comment]
https://github.com/neovim/nvim-lspconfig/blob/03a09b930b6efee91844ccffe96cb3fcc01da385/doc/lspconfig.txt#L158

**Comment by pappasam** [comment]
```

**Comment by dpopchev** [comment]
GREAT! 5 days of pain ended!
```
require('lspconfig')['jedi_language_server'].setup{
    on_attach = on_attach,
    flags = lsp_flags,
    root_dir = require("lspconfig/util").root_pattern(".git"),
    init_options = {
            workspace = {
                extraPaths = {'./lib'}
            }
        }
}
```

**Comment by pappasam** [comment]
:+1:
