### ISSUE TITLE
Move away from palantir/python-jsonrpc-server

### ISSUE THREAD

**Issue by Foxboron** [pappasam/jedi-language-server#246]
Hi,

It seems like the `python-jsonrpc-server` project from Palantir is mostly dead. It might be a good idea to find a suitable replacement with an active upstream or actively fork the project.

https://github.com/palantir/python-jsonrpc-server

**Comment by krassowski** [comment]
There is a maintained fork: https://github.com/python-lsp/python-lsp-jsonrpc
