### ISSUE TITLE
Missing warning for unresolved imports

### ISSUE THREAD

**Issue by wtfzambo** [pappasam/jedi-language-server#252]
Hello,

there's a high possibility that I'm stupid, but I've been bashing my head against this for the past 4 hours without reaching any meaningful conclusion.

I use VSCode with the Microsoft Python plugin, and I recently switched to Jedi Language server because imho it parses docstrings better than PyLance does.

However, contrarily to PyLance, it doesn't warn me about unresolved imports. E.g. on a newly created python virtual environment with nothing installed:

- With PyLance:
> ![image](https://user-images.githubusercontent.com/47462792/213475641-2aa90b4a-8e6b-4bfd-8df6-1eb2fde854b2.png)

- With Jedi:
> ![image](https://user-images.githubusercontent.com/47462792/213476184-5d512745-5a2d-4b2f-90e5-d5336c326399.png)

As you can see, it doesn't warn me about pandas import not being able to resolve.
Which is extra weird since Jedi is still able to resolve installed modules, as it properly shows documentation and autocomplete for them, e.g.:
> ![image](https://user-images.githubusercontent.com/47462792/213476762-df3b0843-3ba0-46e7-b2d1-b92923deaa64.png)

Current specs:
- Python version: 3.10
- Vscode version: 1.74.3
- OS: Win11

What am I doing wrong?

**Comment by pappasam** [comment]
At this time, `jedi-language-server` doesn't provide those sorts of diagnostics, because Jedi does not provide them.

See here: https://github.com/pappasam/jedi-language-server#diagnostics

Related issue: https://github.com/pappasam/jedi-language-server#diagnostics

**Comment by wtfzambo** [comment]
@pappasam sorry for the extra message, but I had to ask: is there a way one can use the features of Jedi and still be able to be warned about unresolved imports, or that's just impossible?

**Comment by davidhalter** [comment]
In theory that's probably possible, because you could use one language server for one completions and another one for diagnostics. But I feel like most editors probably did not implement that. Not sure about VSCode.

**Comment by wtfzambo** [comment]
@davidhalter 

I noticed that Pylint seems able to report unresolved imports by itself, thanks anyway!

**Comment by pappasam** [comment]
@wtfzambo David's suggestion is actually how we currently recommend adding additional diagnostics: <https://github.com/pappasam/jedi-language-server#diagnostics>. Using a general purpose language server, you can configure pylint to provide diagnostics for Python files. One option for vscode: https://marketplace.visualstudio.com/items?itemName=Matts966.efm-langserver-vscode

Again, this is "jedi-language-server", not a kitchen-sink "Python language server". It focuses specifically on Jedi, third-party tools like pylint are out of scope for this project.

**Comment by wtfzambo** [comment]
thanks for the additional explanation @pappasam . To be honest, I feel like I still barely understand language servers in general, for example I'm still not sure what the difference between Jedi and Jedi Language Server is 😅
