### ISSUE TITLE
[question] a way to ignore sub-directories

### ISSUE THREAD

**Issue by FelipeLema** [pappasam/jedi-language-server#265]
hey, everyone

first: thanks all maintainers for this LSP implementation. I keep coming back to all things jedi so often.

now, here's the situation: I'm using `git worktrees` with `.worktrees` as sub-directory (main branch is at `$REPO_DIR`, branches are at `$REPO_DIR/.worktrees/some-branch`, `$REPO_DIR/.worktrees/other-branch` …). Many tools (say `ripgrep`) will handle this correctly (`rg` will _not_ search under `$REPO_DIR/.worktrees`) although I'm not sure if this is because they ignore hidden directories (they start with a `.`) or they call `git` underneath to get a list of paths to ignore.

Regardless, jedi-language-server will recurse files in `$REPO_DIR/.worktrees` when I don't want it to. 

Is there a way to tell jedi-language-server to skip recursing `$REPO_DIR/.worktrees` ?

**Comment by pappasam** [comment]
Which specific LSP call are you using? If you're trying to retrieve symbols, you can ignore directories with this option: https://github.com/pappasam/coc-jedi#jediworkspacesymbolsignorefolders

**Comment by FelipeLema** [comment]
references ( `vim.lsp.buf.references()` in neovim)

seems that using `jedi.workspace.symbols.ignoreFolders` is not working 🤔  

tried both settings below

```lua
settings = {
  ['jedi.workspace.symbols.ignoreFolders'] = {
    ".nox", ".tox", ".venv", "__pycache__", "venv",
    ".worktrees"
  }
}
```

```lua
settings = {
  jedi = {
    workspace = {
      symbols = {
        ignoreFolders = {
          ".nox", ".tox", ".venv", "__pycache__", "venv",
          ".worktrees"
        }
      }
    }
  }
}
```

**Comment by pappasam** [comment]
This project doesn't use "settings", you'll need to use initializationOptions.

Here are some docs from <https://github.com/neovim/nvim-lspconfig/blob/6c53bf7fb02a2de7e7c84be7a2bd7a502f66a802/doc/lspconfig.txt#L158]>. I use coc, so I don't know the full config off the top of my head for you.

**Comment by pappasam** [comment]
https://neovim.discourse.group/t/pyls-and-jedi-language-server-100-cpu-usage/233/16

**Comment by FelipeLema** [comment]
thanks for your suggestions @pappasam, although they don't seem to be working for me
```
    init_options = {
      jedi = {
        workspace = {
          symbols = {
            ignoreFolders = {
              ".nox", ".tox", ".venv", "__pycache__", "venv",
              ".worktrees"
            }
          }
        }
      }
    }
```

maybe I'm missing something, but will close since there is a way to ignore directories

if it's not working due to a bug, I will open a separate issue
