### ISSUE TITLE
Pydantic-core build failures. "Unsupported Python Interpreter: python3.10"

### ISSUE THREAD

**Issue by anoduck** [pappasam/jedi-language-server#279]
Python packages that require cross compilation of rust libraries almost always fail to build in OpenBSD systems. I imagine the same goes for other BSD based systems as well. This is due to the difference in required permissions and facilitating a different C compiler. They always fail when attempting to compile the maturin package.

**Comment by pappasam** [comment]
Should be resolved in https://github.com/pappasam/jedi-language-server/releases/tag/v0.41.1 , which removes the pydantic dependency

**Comment by anoduck** [comment]
@pappasam Holy Shit! This is terrific news. May god be with you.
