### ISSUE TITLE
LSP values aren't being injected into `nvim-cmp`

### ISSUE THREAD

**Issue by scallaway** [pappasam/jedi-language-server#286]
Hi there!

I've discovered this after getting frustrated with the performance of Pyright, and all is going well so far.

The only thing that I'm missing is the indexed values that JLS has found being injected into `nvim-cmp`, like you get in Pyright.

My current LSP Config, JLS setup looks like this:
```lua
    require("lspconfig").jedi_language_server.setup({
        on_attach = on_attach,
        capabilities = capabilities,
    })
```

Since that's all I really had to do with Pyright. I'm not sure whether it's a lack of capabilities or similar?

I tried searching through the issues on here, but couldn't find anything.

Any help on this would be great!

**Comment by epsentosa** [comment]
i think i have similar issue when using JLS
<img width="1144" alt="Screenshot 2023-10-19 at 13 36 04" src="https://github.com/pappasam/jedi-language-server/assets/96678035/e4e35342-2722-49d2-8032-8f620f2aef98">

**Comment by pappasam** [comment]
By "indexed values", what do you mean? Screenshot appreciated! I've just switched from coc to the built-in lsp, and things appear to be working fine for me with nvim-cmp.

**Comment by davidhalter** [comment]
@scallaway I'm currently rewriting Jedi & Mypy in Rust and your use case feels interesting. Would you mind sharing a few more details about when Pyright is slow via Email? You find my email on my profile.

**Comment by scallaway** [comment]
REalised I haven't come back to this in _ages_, but I've just had another play around with JLS and it appears to be working fine now.

I'm not sure whether my config now has changed since I posted this (it's pretty much always evolving, available at @scallaway/nvim), but I'm going to try and continue to use JLS going forward.

Thanks all for checking in on this issue though!

@davidhalter I'll compose a detailed email to you when I get a chance

**Comment by pappasam** [comment]
:+1:
