### ISSUE TITLE
Why is Go to implementation not implemented?

### ISSUE THREAD

**Issue by antoniogamiz** [pappasam/jedi-language-server#303]
Hi,

I'm trying to go use the go to implementation feature of the lsp in neovim, but it is not supported by the LSP. Any idea why? It says 

```
method textDocument/implementation is not supported by any of the servers registered for the current buffer.
```

It seems to be true, that method does not seem supported here, but I would like to know why. I'm trying to use it to go from an interface declaration to its implementation.

**Comment by pappasam** [comment]
Relates to this discussion, please continue the conversation there: https://github.com/pappasam/jedi-language-server/issues/284
