### ISSUE TITLE
feature request: filter out special methods / magic methods from completion

### ISSUE THREAD

**Issue by FelipeLema** [pappasam/jedi-language-server#314]
some, but not limited to:
```
__eq__
__ge__
__gt__
__le__
__lt__
__ne__
__dir__
__new__
__str__
```

**Comment by pappasam** [comment]
Have you tried out the `completion.ignorePatterns` configuration option? I'd imagine something like `__*` might solve this for you.

**Comment by FelipeLema** [comment]
that'll do, thanks
