### ISSUE TITLE
Jedi doesn’t seem to know about the int.bit_count method

### ISSUE THREAD

**Issue by Openstreetmapler** [pappasam/jedi-language-server#328]
_Originally submitted at https://github.com/microsoft/pylance-release/issues/6786_

----

## Environment data

-   Jedi language server version: unknown, shipped with the VSCodium version of the [Microsoft VSCode Python extension](https://github.com/microsoft/vscode-python), extension ID `ms-python.python`, version 2024.22.0
-   OS and version: Ubuntu 22.04 and macOS 12.7.5
-   Python versions: Python 3.10.12 on Ubuntu, 3.10.7 on macOS

## Code Snippet

Type the following into VSCodium:
```python
number = 123
number.bit_count()
```
While typing the second line, the Python extension will suggest `bit_length` but *not* `bit_count` even though the latter function was added to the `int` class with Python 3.10.

## Expected behavior

After typing `number.bit_`, both `bit_count` and `bit_length` are suggested as auto-completions.

## Actual behavior

After typing `number.bit_`, only `bit_length` is suggested.

## Logs

N/A – I don’t think this issue needs a log trace as it’s just a missing feature or oversight, in my opinion.

**Comment by davidhalter** [comment]
This is most likely, because typeshed is outdated in Jedi and should be added.

**Comment by davidhalter** [comment]
This is the relevant issue: https://github.com/davidhalter/jedi/issues/2009

This issue should probably be closed.
