### ISSUE TITLE
Starting the server

### ISSUE THREAD

**Issue by cwagner2046** [pappasam/jedi-language-server#40]
Hi, I followed your instructions to install jedi-language-server: pip install jedi-language-server.
(This is a first installation. The Python version is 3.8.5.)

The package is installed but the command "jedi-language-server" is not installed, or is not
installed in a directory featuring in the PATH.

Am I missing something?

**Comment by pappasam** [comment]
@cwagner2046 did you install it within a virtualenv? Are you using asdf? Are you using your system python? What is your OS?

If you're using asdf: `asdf reshim python`

If you're using a virtualenv: deactivate and reactive the virtualenv

If you're using something else, you'll need to provide more information for me to help you.

**Comment by cwagner2046** [comment]
Hi, I just followed the sequence of actions described in the README file:

1. install with pip

**Comment by pappasam** [comment]
Fantastic observation! You may have just discovered a flaw in the documentation.

As I've already requested, would you please provide more information about your environment?

**Comment by cwagner2046** [comment]
Hi, I had to edit my comment and, therefore, you may have not seen all of it. Considering its content, do still require more information? If so, which one? Thanks.

**Comment by cwagner2046** [comment]
I have found the jedi-language-server program. My installation of Python is based on Mac OSX
frameworks. This entails certain subtleties of which I was not aware. Amongst them are
the location where pip installs scripts, location which is /Library/Frameworks/Python.framework/Versions/3.8/bin in the case of Python 3.

I'm closing the issue because it is clear now that there are no issues with your doc. Sorry
for the trouble.
