### ISSUE TITLE
ValueError: `column` parameter is not in a valid range

### ISSUE THREAD

**Issue by subsonik** [pappasam/jedi-language-server#42]
Hi!

Great work with this project, this has recently become my favourite LSP server to use while coding with Python in Neovim (latest HEAD). It's nice to have a lightweight alternative to pyls. 😀

However, I'm experiencing a fairly recurrent error that occurs when exiting insert mode. The error message returned from vim-lsc (my Neovim LSP client) is:

> ValueError: `column` parameter (36) is not in a valid range (0-34) for line 7 ('from dataclasses import asdict, fi\n').

It doesn't happen all of the time, only when exiting insert mode after extending an already-existing line with more text, e.g. changing `from dataclasses import asdict` to `from dataclasses import asdict, field`.

This doesn't occur with pyls. I think they had the same issue, which was raise and fixed here: https://github.com/palantir/python-language-server/issues/193

Any chance you could take a look at this?

Thanks.

**Comment by pappasam** [comment]
Thanks for this issue! I've implemented and released a solution based on the pyls PR from the long-long ago. If you have time, would you try the latest release and close this issue if your problem is resolved?

**Comment by subsonik** [comment]
Works like a charm! Thanks for the speedy response and your great work on this project. 😁
