### ISSUE TITLE
Add a comparison to pyls

### ISSUE THREAD

**Issue by KOLANICH** [pappasam/jedi-language-server#43]
Not only by features, but by resources consumption too.

**Comment by pappasam** [comment]
I'd love this! I haven't used that language server for a long time, but it would be great if someone with recent pyls experience and the will to compare it rigorously to jedi-language-server were able to put something helpful together. At the very least, it could help me determine whether there are any outstanding development efforts that I can look into.

**Comment by pappasam** [comment]
Not really sure this is relevant anymore, but feel free to open a PR with any benchmarking with other projects!
