### ISSUE TITLE
How to show documentation when entering function parameters?

### ISSUE THREAD

**Issue by quantum-booty** [pappasam/jedi-language-server#44]
I am using the jedi-ls with Nvim-lsp.
When using pyls, the documentation shows when I am writing function parameters, whereas jedi-ls only shows the signature help. How can I replicate the behaviour like in pyls?

Pyls:
![image](https://user-images.githubusercontent.com/28958399/97060532-84f1ab00-158b-11eb-9aac-6bdcafb61be1.png)

Jedi-ls:
![image](https://user-images.githubusercontent.com/28958399/97060643-e87bd880-158b-11eb-9000-ff3e6b272cad.png)

**Comment by pappasam** [comment]
Ah, this is something I'd ideally like to support, but I've run into some issues with nvim-lsp and its treatment of undefined values that has made me shy away from implementing this feature at this time.

In short, there's a pygls limitation at present where Python's `None` is treated as both Javascript `undefined` and `null`. nvim-lsp does not handle `null` and `undefined` in an elegant way, which will break your language server. To get around this / support Neovim's native language server, I've avoided adding this feature.

See https://github.com/pappasam/jedi-language-server/issues/38

That said, if you were able to verify that Neovim's lsp implementation tolerates this ambiguity between `null` and `undefined` (coc currently tolerates it), I'd be happy to implement!

**Comment by pappasam** [comment]
Also see my pull request with pygls: <https://github.com/openlawlibrary/pygls/pull/132>. It's been completely ignored, so I'm not sure solutions to this problem are being prioritized at this time.

**Comment by pappasam** [comment]
And here's the pygls issue: https://github.com/openlawlibrary/pygls/issues/124
