### ISSUE TITLE
Code Actions problems

### ISSUE THREAD

**Issue by daliusd** [pappasam/jedi-language-server#47]
I'm experimenting with LSP Code Actions in Ale and one person suggested that `jedi-language-server` is good candidate for testing code actions. However I usually get quite not perfect results with it. Let's say I have following python file:

```python

def main():
    a = 1
    b = 2
    c = a + b
```

I give instructions to extract function for code starting with line `a = 1` and ending with last line. The result is following (notice that `return` is in wrong line):

```

def func_dfouerpw():
    a = 1
    b = 2
    c = a + b    return c


def main():
    c = func_dfouerpw()

```

Here is JSON (vimscript format) that I get from jedi-language-server:
```
{'id': 7, 'jsonrpc': '2.0', 'result': [{'diagnostics': v:null, 'edit': {'changes': v:null, 'documentChanges': [{'edits': [{'range': {'end': {'character': 7, 'line': 1}, 'start': {'character': 4, 'line': 1}}, 'newText': 'fu'}, {'range': {'end': {'character': 8, 'line': 1}, 'start': {'character': 8, 'line': 1}}, 'newText': 'c_dfouerpw'}, {'range': {'end': {'character': 14, 'line': 4}, 'start': {'character': 14, 'line': 4}}, 'newText': '    return c^@^@^@def main():^@    c = func_dfouerpw()^@'}], 'textDocument': {'uri': 'file:///Users/daliusd/projects/photoscripts/test.py', 'version': v:null}}]}, 'kind': 'refactor.extract', 'title': 'Extract expression into function ''func_dfouerpw''', 'command': v:null}]}
```

I have not tested `jedi-language-server` with other LSP implementations but could it be that there is problem in `jedi-language-server` side.

**Comment by daliusd** [comment]
I think problem is in out side. It looks like existing code is ignoring existing end-of-lines.

**Comment by pappasam** [comment]
@daliusd greatw, thanks! And please let me know if you discover that it is, in fact, a problem with jedi-language-server. I'd definitely want to fix that if it were that case.

**Comment by daliusd** [comment]
Hey, thanks for confirming it. It was problem in Ale's code and I hope I have fixed it. I will ask people to do more testing and let's see what will happen 😀
