### ISSUE TITLE
How to use it with vscode?

### ISSUE THREAD

**Issue by proofit404** [pappasam/jedi-language-server#50]
README mentions only great editors like vim & emacs.

Is it possible to configure vscode to use this server?

Regards,
Artem.

**Comment by pappasam** [comment]
Great question! I don't use vscode so I'm not 100% sure, but I assume we'll need to write a VSCode client as documented [here](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#implementing-a-language-server). Based on the fact that [coc.nvim](https://github.com/neoclide/coc.nvim) is somewhat based on vscode and that I've already written a [language server extension for coc.nvim](https://github.com/pappasam/coc-jedi), it would probably be a matter of porting coc-jedi to support VSCode.

**Comment by QDelage** [comment]
Isn't that the one used when you put
`"python.languageServer": "Jedi"` 
in your settings.json ?

**Comment by pappasam** [comment]
@QDelage no, that configuration comes from vscode-python, an existing vscode extension maintained by microsoft that does not use `jedi-language-server` (instead optionally relying on `jedi` itself for some language server functionality). See <https://github.com/microsoft/vscode-python/issues/7010>

**Comment by karthiknadig** [comment]
With the latest release of VS Code https://github.com/microsoft/vscode-python/releases/tag/2021.2.576481509 there is a new setting for `python.languageServer` for this.  Set `python.languageServer` to `JediLSP`. This is still experimental, and uses older version (for now) to support python 2.7.

**Comment by pappasam** [comment]
I've added the comment above to the readme. We can call this resolved for now and update the readme with any new instructions as/if the VSCode integration evolves.
