### ISSUE TITLE
Testing on the command line

### ISSUE THREAD

**Issue by markuspalme** [pappasam/jedi-language-server#51]
The server supports communiction over STDIO. But I'm not able to get any answer out of if when running it on the command line.

I'm trying to run an intialize request here:

![grafik](https://user-images.githubusercontent.com/1481801/100645741-61194600-333d-11eb-922b-736706e33803.png)

Pressing enter does not lead to a result. I must be missing something very basic here. Any help would be appreciated!

**Comment by pappasam** [comment]
In general, `jedi-language-server` must be run as a subprocess by your editor. If using neovim / coc.nvim, I suggest that you use

**Comment by markuspalme** [comment]
I know that, but I want to test the communication in a more basic way. Shouldn't it response to STDOUT on the command line?

**Comment by pappasam** [comment]
Possibly, but I'm not personally aware of how to do that. If you figure anything out, please let me know and I'll happily add what you learn to the readme!

**Comment by markuspalme** [comment]
Ok, the `pygls` server waits until it finds this pattern in the input:

`CONTENT_LENGTH_PATTERN = re.compile(rb'^Content-Length: (\d+)\r\n$')` 

The problem is the windows line end `\r\n`, this is hard to type in a terminal. Windows terminal even converts it to `\n` when pasting. I could not get interactive testing to work, but reading the input from a file works in PowerShell:

` get-content request.json | jedi-language-server`

On Linux, this should work:

`jedi-language-server < request.json`

**Comment by pappasam** [comment]
@markuspalme would you be able to paste an example request here? If possible, I'd like to add your above example to the readme. That, or I'd always appreciate a PR from you with the example in the README if you have the time. Thanks in advance!

**Comment by markuspalme** [comment]
Sorry, I don't have a working example for `jedi-language-server`. I have switched to `python-language-server` for compatibility reasons with `monaco-languageclient`.
