### ISSUE TITLE
Renaming merges two lines

### ISSUE THREAD

**Issue by astier** [pappasam/jedi-language-server#63]
## Info

NVIM v0.5.0-dev+1073-gb894fbcbe
jedi-language-server, version 0.21.0
Python 3.9.1

## Problem

Renaming a variable merges the line where the variable is defined with the line above.

## Minimal init.vim

```vim
set runtimepath^=~/.local/share/nvim/plugins/nvim-lspconfig
lua require 'lspconfig'.jedi_language_server.setup{}
nnoremap gr :lua vim.lsp.buf.rename()<cr>
```

## Minimal bug.py

```py
# bug incoming
x = 1
```

## Reproduce

1. Install neovim-nightly
1. Install [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) and put it on nvims runtimepath. In my case its `~/.local/share/nvim/plugins/nvim-lspconfig`
1. Create minimal vimrc and bug.py
1. Open bug.py with neovim
1. Move cursor on the variable `x`
1. Type `gr` and rename variable to y

The comment and the variable are now merged into a single line:

```py
# bug incomingx = 1
```

I tried the same setup with the python-language-server and it worked without the bug.

**Comment by pappasam** [comment]
Interesting... I just tested your example with `coc-jedi` on Python `3.8.6` and don't observe the bug. This will take some more digging, will try mimicking your environment to reproduce when I get some time.
