### ISSUE TITLE
No completion for matplotlib's subplot when using their new coding format

### ISSUE THREAD

**Issue by listout** [pappasam/jedi-language-server#64]
I was following the coding format from [the 3.1.0 doc](https://matplotlib.org/3.1.0/gallery/subplots_axes_and_figures/subplots_demo.html). I believe they call this the new object oriented approach.

I was not able to get completions, how ever if I use subplots in regular approach I get completions as expected.

**Codes and Screenshots**

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 2 * np.pi, 400)
y = np.sin(x ** 2)

fig, (ax1, ax2) = plt.subplots(2)

fig.suptitle('Vertical stacked plots') # autocomplete here too
ax1.
```

![python1](https://user-images.githubusercontent.com/66715002/107322078-c28e2b80-6ac9-11eb-9d97-1b156a9addb9.png)

However after writing the complete functions, jedi language server doesn't show any error too, checked with both native jedi language server and pylint.

**Information**

Environment: I use coc-jedi with the coc.nvim plugin in vim/nvim.
OS: Linux
Editor: Vim/Neovim with coc.nvim as an lsp client

**Comment by listout** [comment]
Found a similar [issue](https://github.com/microsoft/python-language-server/issues/1989#issuecomment-611643566)

**Comment by pappasam** [comment]
In this case, I think you're in luck! Jedi is smart enough to understand type hints, and there are typehints for matplotlib / numpy / pandas provided in another package!

https://pypi.org/project/data-science-types/

Just install that package in your project and you should be good to go!
