### ISSUE TITLE
Add initialization option to change limit on workspace symbols

### ISSUE THREAD

**Issue by karthiknadig** [pappasam/jedi-language-server#76]
Currently workspace symbols are limited 20. This should be a setting that can be controlled via initialization options, with following interpretation:
* `0` to mean disable limit.
* `>0` as the number of symbols to limit.

**Comment by pappasam** [comment]
@karthiknadig Any reason for the `>0` versus `0`? Does this match some universal interface?

Is there is no strong justification, I think I'll just take an integer and interpret anything less than or equal to 0 as disabling the limit.

**Comment by pappasam** [comment]
Released in 0.26.0

**Comment by karthiknadig** [comment]
Thanks for adding this :) 

> I think I'll just take an integer and interpret anything less than or equal to 0 as disabling the limit.

This works.
