### ISSUE TITLE
No diagnostics with nvim-lsp

### ISSUE THREAD

**Issue by khaveesh** [pappasam/jedi-language-server#77]
I checked in the debug logs and the payload for publishDiagnostics is empty. For cross-checking, I used pyls and I did get error messages.

I'm initialising the language server with pure defaults. But, AFAIK it should publish the diagnostics on open, change and save, which is not working.

**Comment by pappasam** [comment]
@khaveesh unlike pyls, jedi-language-server only shows diagnostic messages from jedi itself, see [here](https://github.com/pappasam/jedi-language-server#additional-diagnostics). I recommend using diagnostic language server if you want diagnostics from tools like pylint, mypy, etc.

If you're not seeing jedi-powered diagnostic messages and expect to, then that would be a problem. To test, put the following lines in your editor:

```python
x = 12

y = \x + 12
```

You should have a diagnostic message under the underline saying `[jedi] [E] SyntaxError: unexpected character after line continuation character`. Do you see this message? If not, would you please provide some more information, such as your nvim-lsp configuration settings. Thanks!

**Comment by khaveesh** [comment]
@pappasam Indeed, I got the error message with this snippet. I had tried out various would-be syntax errors like using undeclared variables, non-existent imports etc, but didn't get diagnostics. If I understand correctly, Jedi provides only parser errors, not syntax errors that you would encounter when running the file through python. If so is there any option to make Jedi include syntax errors too?

And also, if I enable snippet support through nvim-lsp, the completion for all functions includes placeholders for all optional arguments too. It is not easy to delete them one by one, since an essential function like print has 5 optional arguments. So, I would recommend that you provide only the parentheses as part of the snippet and not the arguments too. If you want, I'll open a separate issue for this. TIA.

**Comment by pappasam** [comment]
1. I'm not aware of any configuration within Jedi that would highlight syntax errors. If you want that, I recommend opening an issue withing [jedi](https://github.com/davidhalter/jedi). Just so you know, the author has considered additional linting messages over the years and further progress has either been rejected or paused. For example, see [here](https://github.com/davidhalter/jedi/issues/600)
2. Yes, we shouldn't be completing snippets for function arguments with defaults. I've noticed a few edge cases where default arguments are completed, but that doesn't happen all the time. Please open a new issue for this, along with a code snippet of an example where a snippet includes the default arguments for a function?

**Comment by pappasam** [comment]
For example, the following example does not complete the default argument in a snippet:

```python
def test(x: str, y: str, z=12) -> None:
    pass

y = test(x, y)
```

**Comment by khaveesh** [comment]
@pappasam It does work properly in this case. But for `print` function it completes with `print(sep=..., end=..., file=..., flush=...)` and for all matplotlib functions, it includes optional arguments too. For example, `plot` completes with `plt.plot(scalex=..., scaley=..., data=...)` where `...` are the placeholders for the snippet

**Comment by pappasam** [comment]
@khaveesh please try the latest release and let me know if it fixes the snippet issue you've identified!

**Comment by khaveesh** [comment]
@pappasam Yep, it fixes the snippets issue.
