### ISSUE TITLE
Adding jedi-language-server to nixpkgs?

### ISSUE THREAD

**Issue by noib3** [pappasam/jedi-language-server#81]
Is it possible to add this package to the nixpkgs repository? Other python language servers are present but I really like this one and it seems to be the only one missing.

**Comment by pappasam** [comment]
I'm all for this!

**Comment by pappasam** [comment]
@noib3 it looks like jedi-language-server has been added to nix's unstable channel: <https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=jedi-language-server>, so I believe we can consider this resolved. Please let me know if you feel otherwise!
